Task_2_3_1
MIZINCHIK/OOP pull request #11
Opened 2023-04-11 10:42 UTC by MIZINCHIK

2023-05-01 17:54 UTC, alradish requested changes

2023-05-01 17:54 UTC, alradish commented on Task_2_3_1/src/main/java/io/github/mizinchik/SnakeModel.java
> +public class SnakeModel {
Модель не должна протекать в GUI и обратно. Плюс выделите модель в отдельный пакет

2023-05-01 17:54 UTC, alradish commented on Task_2_3_1/src/main/java/io/github/mizinchik/utils/Snake.java
> +public class Snake extends Point {
Почему змея расширяет поинт? Как-то это неправильно

2023-05-01 17:54 UTC, alradish commented on Task_2_3_1/src/main/java/io/github/mizinchik/utils/Snake.java
> +    public void move(boolean foodEaten) {
Что-то я запутался. Если змея съела еду то не должен удаляться хвост

2023-05-08 16:35 UTC, MIZINCHIK commented
Раз мы показываем приложение на паре, в jar собирать не нужно?

2023-05-16 08:05 UTC, alradish commented
- Обработка ошибок
- Сколько осталось до победы
- `в начале игры змейка состоит из одного звена`
- `в каждый момент времени на игровом поле находится «T» элементов еды, занимающей одну клетку поля`

2023-05-16 08:22 UTC, alradish requested changes
^

2023-05-16 08:22 UTC, alradish requested changes
^

2023-05-23 07:31 UTC, alradish approved these changes

2023-05-23 07:42 UTC, merged