Task_1_2_1
MIZINCHIK/OOP pull request #2
Opened 2022-09-25 14:05 UTC by MIZINCHIK

How to handle exceptions w/o a main section? I'm throwing them and catching them at the same exact time. Hence I can't even test them with JUnit (commented out an example of such test). And if I'm not catching the exceptions I get warnings.

2022-09-26 12:40 UTC, Leidenn2509 requested changes

2022-09-26 12:40 UTC, Leidenn2509 commented on Task_1_2_1/src/main/java/io/github/mizinchik/Stack.java
> +    }
[Objects.requireNonNull()](https://stackoverflow.com/questions/45632920/why-should-one-use-objects-requirenonnull) хорошая штука, и вроде как делает именно то, для чего вы написали эти функции

2022-09-26 12:40 UTC, Leidenn2509 commented on Task_1_2_1/src/main/java/io/github/mizinchik/Stack.java
> +        if (this.stackSize == this.lastElementIndex + 1) {
`this` no more

2022-09-26 12:40 UTC, Leidenn2509 commented on Task_1_2_1/src/main/java/io/github/mizinchik/Stack.java
> +    public T pop() throws EmptyStackException {
Добавьте уменьшение массива

2022-09-26 13:10 UTC, MIZINCHIK commented on Task_1_2_1/src/main/java/io/github/mizinchik/Stack.java
> +        if (this.stackSize == this.lastElementIndex + 1) {
а зачем тогда this нужен 😳

2022-09-29 09:12 UTC, Leidenn2509 commented on Task_1_2_1/src/main/java/io/github/mizinchik/Stack.java
> +        if (this.stackSize == this.lastElementIndex + 1) {
Так здесь он как раз таки не нужен. Его используют там, где без него никак, например в конструкторе, когда нужно инициализировать поле имя которого совпадает с именем параметра

2022-09-29 09:16 UTC, alradish approved these changes

2022-09-29 09:16 UTC, merged