Task_1_4_1
MIZINCHIK/OOP pull request #6
Opened 2022-11-22 17:03 UTC by MIZINCHIK

2022-11-26 12:58 UTC, pelageech commented on Task_1_4_1/src/test/java/io/github/mizinchik/GradeBookTest.java
> +import java.nio.charset.StandardCharsets;
навалил кринжа

2022-11-26 12:59 UTC, MIZINCHIK commented on Task_1_4_1/src/test/java/io/github/mizinchik/GradeBookTest.java
> +import java.nio.charset.StandardCharsets;
🤡

2022-11-26 14:04 UTC, pelageech approved these changes

2022-12-06 12:29 UTC, alradish requested changes
Task_1_3_1 лишнее
Хорошая работа

2022-12-06 12:29 UTC, alradish commented on Task_1_4_1/src/main/java/io/github/mizinchik/GradeBookImpl.java
> +        return terms.get(term - 1).getGrade(subject);
Сделайте проверки во всех таких местах. Например тут может быть аутофбаундс

2022-12-12 02:27 UTC, alradish approved these changes

2022-12-12 02:29 UTC, merged