Task_2_1_1
MIZINCHIK/OOP pull request #9
Opened 2023-02-13 12:22 UTC by MIZINCHIK

2023-02-14 15:37 UTC, alradish reviewed
good start

2023-02-14 15:38 UTC, alradish requested changes
good start

2023-02-22 07:47 UTC, alradish requested changes
Добавьте ещё бенч на паралел стрим

2023-02-22 07:47 UTC, alradish commented on Task_2_1_1/src/main/java/io/github/mizinchik/CompositeArrayStream.java
> +    boolean containsCompositeStream() {
Почему пекедж прайват?

2023-02-22 07:47 UTC, alradish commented on Task_2_1_1/src/main/java/io/github/mizinchik/CompositeArrayStream.java
> +public class CompositeArrayStream extends CompositeArrayConsecutive {
Всё же стоит отнаследоваться от `CompositeArrayInterface` и переопределять метод. Иначе получается что ваш класс умеет находить компосит, но делает это не стрмиом, а последовательно

2023-02-22 07:47 UTC, alradish commented on Task_2_1_1/src/main/java/io/github/mizinchik/CompositeArrayThread.java
> +    public boolean containsComposite(int threadsQuantity) throws InterruptedException {
Опять же, надо переопределить метод

2023-02-22 07:47 UTC, alradish commented on Task_2_1_1/src/main/java/io/github/mizinchik/CompositeArrayThread.java
> +            int leftLimit = getArray().length / threadsQuantity * chunkIndex;
В таких случаях всё же стоит просто запомнить результат getArray в локальную переменную

2023-02-24 14:38 UTC, MIZINCHIK commented
> Добавьте ещё бенч на паралел стрим

Там есть бенч на него

2023-02-27 05:54 UTC, alradish approved these changes

2023-02-27 05:54 UTC, merged